# =============================================================================
# GitHub Secret Scanning Configuration
# =============================================================================
# This file configures which paths and patterns should be excluded from
# GitHub's secret scanning to avoid false positives on sample/test data.

# Paths to exclude from secret scanning
paths-ignore:
  # Database sample/seed data - contains mock credentials and test data
  - 'database/data/**'
  - 'database/scripts/**'

  # Test fixtures and mock data
  - 'tests/fixtures/**'
  - 'tests/mocks/**'
  - 'tests/__fixtures__/**'

  # Documentation and examples
  - 'docs/**'
  - 'examples/**'
  - '*.md'
  - '**/*.md'

  # Build artifacts and dependencies
  - 'node_modules/**'
  - 'dist/**'
  - 'build/**'
  - 'coverage/**'

  # Configuration templates and examples
  - '*.example'
  - '**/*.example'
  - '.env.example'
  - 'config/examples/**'

# File patterns to exclude
patterns-ignore:
  # Sample/test configuration files
  - '*.sample.*'
  - '*.template.*'
  - '*.example.*'

  # Test and mock files
  - '*.test.*'
  - '*.spec.*'
  - '*.mock.*'
  - '**/test-*'
  - '**/mock-*'

  # Documentation files
  - 'README*'
  - 'CHANGELOG*'
  - 'LICENSE*'
  - 'CONTRIBUTING*'
  - 'CODE_OF_CONDUCT*'

# Additional exclusions for specific file types that commonly contain
# sample data that might trigger false positives
file-types-ignore:
  # JSON files in data directories (sample data)
  - 'database/**/*.json'
  - 'data/**/*.json'
  - 'fixtures/**/*.json'
  - 'samples/**/*.json'

  # SQL files with sample data
  - 'database/**/*.sql'
  - 'data/**/*.sql'
  - 'seeds/**/*.sql'

  # YAML files in test/config directories
  - 'tests/**/*.yml'
  - 'tests/**/*.yaml'
  - 'config/samples/**/*.yml'
  - 'config/samples/**/*.yaml'
