# docker-compose.override.yml
# This file is automatically loaded in development
# Contains development-specific overrides

services:
  user-service:
    image: user-service:dev
    build:
      context: .
      target: development
    ports:
      - '${PORT:-3002}:${PORT:-3002}'
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    command: npm run dev
    environment:
      - NODE_ENV=development
    networks:
      - aioutlet-dev-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.user-service.rule=PathPrefix(`/api/users`)'
      - 'traefik.http.routers.user-service.entrypoints=web'

  mongo-user-service:
    ports:
      - '${MONGODB_PORT:-27017}:27017'
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - aioutlet-dev-network

networks:
  aioutlet-dev-network:
    driver: bridge
    name: aioutlet-dev-network
    labels:
      - 'com.aioutlet.environment=development'
      - 'com.aioutlet.network=dev'
