version: '3.8'
services:
  user-service-db:
    image: mongo:6.0
    container_name: user-service-db
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: user-service-db
      MONGO_INITDB_ROOT_USERNAME: useradmin
      MONGO_INITDB_ROOT_PASSWORD: userpassword
    volumes:
      - user-service-db-data:/data/db
volumes:
  user-service-db-data:
