apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: user-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    # RabbitMQ connection using connectionString (recommended)
    - name: connectionString
      value: 'amqp://admin:admin123@127.0.0.1:5672'
    - name: consumerID
      value: 'user-service'
    - name: durable
      value: 'true'
    - name: deletedWhenUnused
      value: 'false'
    - name: autoAck
      value: 'false'
    - name: deliveryMode
      value: '2' # Persistent messages
    - name: requeueInFailure
      value: 'true'
    - name: prefetchCount
      value: '10'
    - name: reconnectWait
      value: '5'
    - name: concurrency
      value: 'parallel'
    # Exchange configuration
    - name: exchangeKind
      value: 'topic'
scopes:
  - user-service
